

const CHANGE_USER_STATE = 'CHANGE_USER_STATE'
const CHANGE_USER_INFO = 'CHANGE_USER_INFO'
const CHANGE_CART_GOODS ='CHANGE_CART_GOODS'
export  { CHANGE_USER_STATE, CHANGE_USER_INFO, CHANGE_CART_GOODS }